[build]
builder = "DOCKERFILE"
dockerfilePath = "Bokoma_Backend/Dockerfile"

[deploy]
startCommand = "cd Bokoma_Backend && node ./src/server.js"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5